# Use an official image as a parent image
FROM alpine:latest

# Install Git
RUN apk add --no-cache git

# Set the working directory
WORKDIR /usr/src/app

# Command to run when the container starts
CMD ["sh"]